import exception.except_sample as es


if __name__ == '__main__':
    es.errorpa()
